<?php

return [
    'modules' => [
        'dashboard' => [
            'label' => 'Dashboard & Overview',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'widget',
                    'class' => \App\Filament\Widgets\DashboardStats::class,
                    'label' => 'Dashboard Stats Widget',
                    'required_methods' => ['render'],
                    'ready_when' => 'Widget renders KPI stats on dashboard',
                ],
                [
                    'type' => 'widget',
                    'class' => \App\Filament\Widgets\SalesTrendChart::class,
                    'label' => 'Sales Trend Chart',
                    'required_methods' => ['render'],
                    'ready_when' => 'Widget shows sales trend line chart',
                ],
                [
                    'type' => 'widget',
                    'class' => \App\Filament\Widgets\TopProductsChart::class,
                    'label' => 'Top Products Chart',
                    'required_methods' => ['render'],
                    'ready_when' => 'Widget shows top products bar chart',
                ],
                [
                    'type' => 'widget',
                    'class' => \App\Filament\Widgets\SystemHealthWidget::class,
                    'label' => 'System Health Widget',
                    'required_methods' => ['render'],
                    'ready_when' => 'Widget shows system health indicators',
                ],
            ],
        ],
        'users' => [
            'label' => 'Users & Customers',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\UserResource::class,
                    'label' => 'User Resource',
                    'required_methods' => ['form', 'table', 'getRelations', 'getPages'],
                    'ready_when' => 'Full CRUD with filters, actions, bulk actions, permissions',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\CustomerSegments::class,
                    'label' => 'Customer Segments',
                    'route' => '/admin/users/segments',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page allows creating/editing customer segments with rules',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\CustomerDetail::class,
                    'label' => 'Customer Detail View',
                    'route' => '/admin/users/{id}',
                    'required_methods' => ['mount'],
                    'ready_when' => 'Page shows customer details, orders, wallet, activity',
                ],
            ],
        ],
        'roles' => [
            'label' => 'Roles & Permissions',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\RoleResource::class,
                    'label' => 'Role Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for roles with permission assignment',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\PermissionResource::class,
                    'label' => 'Permission Resource',
                    'required_methods' => ['table'],
                    'ready_when' => 'View-only list of permissions with filters',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\UserRoleAssignment::class,
                    'label' => 'User Role Assignment',
                    'route' => '/admin/roles/assign',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page allows bulk role assignment to users',
                ],
            ],
        ],
        'catalog' => [
            'label' => 'Catalog Management',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\ProductResource::class,
                    'label' => 'Product Resource',
                    'required_methods' => ['form', 'table', 'getRelations', 'getPages'],
                    'ready_when' => 'Full CRUD with variants, images, pricing, inventory, SEO',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\CategoryResource::class,
                    'label' => 'Category Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD with hierarchy, images, SEO',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\BrandResource::class,
                    'label' => 'Brand Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD with logo upload, description, SEO',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\AttributeResource::class,
                    'label' => 'Attribute Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for product attributes (size, color, etc.)',
                ],
            ],
        ],
        'orders' => [
            'label' => 'Orders & Fulfillment',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\OrderResource::class,
                    'label' => 'Order Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD with status transitions, payment info, shipping, items',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\OrderWorkflowBuilder::class,
                    'label' => 'Order Workflow Builder',
                    'route' => '/admin/orders/workflow',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page allows defining custom order statuses and transitions',
                ],
            ],
        ],
        'inventory' => [
            'label' => 'Inventory & Warehousing',
            'priority' => 2,
            'for_codecanyon_mvp' => false,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\StockLedgerResource::class,
                    'label' => 'Stock Ledger Resource',
                    'required_methods' => ['table'],
                    'ready_when' => 'View-only ledger showing stock movements',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\StockAdjustments::class,
                    'label' => 'Stock Adjustments',
                    'route' => '/admin/inventory/adjustments',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page allows manual stock adjustments with audit logs',
                ],
            ],
        ],
        'promotions' => [
            'label' => 'Promotions & Discounts',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\CouponResource::class,
                    'label' => 'Coupon Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD with rules engine, usage limits, scheduling',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\DealResource::class,
                    'label' => 'Deal Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for flash deals with scheduling',
                ],
            ],
        ],
        'payments' => [
            'label' => 'Payment Gateways',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\PaymentSettings::class,
                    'label' => 'Payment Settings',
                    'route' => '/admin/settings/payments',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures payment providers and credentials',
                ],
                [
                    'type' => 'api',
                    'class' => \App\Http\Controllers\Api\v1\PaymentController::class,
                    'label' => 'Payment API',
                    'route' => '/api/v1/payments',
                    'required_methods' => ['create', 'verify'],
                    'ready_when' => 'API handles payment creation and verification',
                ],
            ],
        ],
        'shipping' => [
            'label' => 'Shipping Providers',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\ShippingSettings::class,
                    'label' => 'Shipping Settings',
                    'route' => '/admin/settings/shipping',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures shipping providers and rates',
                ],
            ],
        ],
        'notifications' => [
            'label' => 'Notifications Hub',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\NotificationProviders::class,
                    'label' => 'Notification Providers',
                    'route' => '/admin/notifications/providers',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures notification providers (email, SMS, push)',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\NotificationEventsToggle::class,
                    'label' => 'Notification Events',
                    'route' => '/admin/notifications/events',
                    'required_methods' => ['mount', 'table'],
                    'ready_when' => 'Page toggles notification events per channel with template linking',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\NotificationLogResource::class,
                    'label' => 'Notification Logs',
                    'required_methods' => ['table'],
                    'ready_when' => 'View-only logs with filters and retry actions',
                ],
            ],
        ],
        'email_templates' => [
            'label' => 'Email Templates',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\EmailTemplateResource::class,
                    'label' => 'Email Template Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD with template variables, preview, test send',
                ],
            ],
        ],
        'branding' => [
            'label' => 'Branding & App Management',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\BrandingSettings::class,
                    'label' => 'Branding Settings',
                    'route' => '/admin/branding',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page uploads logo, favicon, app name, colors',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\ThemeTokens::class,
                    'label' => 'Theme Tokens',
                    'route' => '/admin/branding/theme',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page edits theme tokens JSON with preview',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\AppVersionControl::class,
                    'label' => 'App Version Control',
                    'route' => '/admin/branding/app-versions',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page manages app versions, min version, force update',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\MaintenanceMode::class,
                    'label' => 'Maintenance Mode',
                    'route' => '/admin/branding/maintenance',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page toggles maintenance mode with message',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\KillSwitch::class,
                    'label' => 'Kill Switch',
                    'route' => '/admin/branding/kill-switch',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page toggles kill switch for emergency shutdown',
                ],
            ],
        ],
        'home_builder' => [
            'label' => 'Home Layout Builder',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\HomeSectionResource::class,
                    'label' => 'Home Section Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for home sections with ordering',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\HomeSectionItemResource::class,
                    'label' => 'Home Section Item Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for section items with images, links, actions',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\MediaAssetResource::class,
                    'label' => 'Media Asset Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for media assets with upload, preview',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\PlacementManager::class,
                    'label' => 'Placement Manager',
                    'route' => '/admin/home-sections/placement',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page allows drag-drop reordering of sections',
                ],
            ],
        ],
        'cms' => [
            'label' => 'Content & CMS',
            'priority' => 2,
            'for_codecanyon_mvp' => false,
            'items' => [
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\CmsPageResource::class,
                    'label' => 'CMS Page Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for CMS pages with SEO, slugs',
                ],
                [
                    'type' => 'resource',
                    'class' => \App\Filament\Resources\ContentStringResource::class,
                    'label' => 'Content String Resource',
                    'required_methods' => ['form', 'table', 'getPages'],
                    'ready_when' => 'Full CRUD for content strings with localization',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\LocalizationManager::class,
                    'label' => 'Localization Manager',
                    'route' => '/admin/cms/localization',
                    'required_methods' => ['mount'],
                    'ready_when' => 'Page manages content localization',
                ],
            ],
        ],
        'settings' => [
            'label' => 'System Settings',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\GeneralSettings::class,
                    'label' => 'General Settings',
                    'route' => '/admin/settings/general',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures app name, timezone, locale',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\AuthSettings::class,
                    'label' => 'Auth Settings',
                    'route' => '/admin/settings/auth',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures Firebase auth, OTP providers',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\NotificationSettings::class,
                    'label' => 'Notification Settings',
                    'route' => '/admin/settings/notifications',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures notification preferences',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\EmailSettings::class,
                    'label' => 'Email Settings',
                    'route' => '/admin/settings/email',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures email SMTP settings',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\StorageSettings::class,
                    'label' => 'Storage Settings',
                    'route' => '/admin/settings/storage',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures storage driver (Local/S3)',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\LanguageSettings::class,
                    'label' => 'Language Settings',
                    'route' => '/admin/settings/languages',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page manages languages and default language',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\TranslationsManager::class,
                    'label' => 'Translations Manager',
                    'route' => '/admin/settings/translations',
                    'required_methods' => ['mount'],
                    'ready_when' => 'Page manages translation strings with import/export',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\Settings\CurrencySettings::class,
                    'label' => 'Currency Settings',
                    'route' => '/admin/settings/currencies',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page manages currencies and exchange rates',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\FeatureFlagsPage::class,
                    'label' => 'Feature Flags',
                    'route' => '/admin/settings/feature-flags',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page toggles feature flags per module',
                ],
            ],
        ],
        'integrations' => [
            'label' => 'Integrations & Providers',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\ProviderCredentialsPage::class,
                    'label' => 'Provider Credentials',
                    'route' => '/admin/integrations/credentials',
                    'required_methods' => ['mount', 'save'],
                    'ready_when' => 'Page configures provider credentials with encryption',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\IntegrationsTester::class,
                    'label' => 'Integrations Tester',
                    'route' => '/admin/integrations/test',
                    'required_methods' => ['mount'],
                    'ready_when' => 'Page tests provider connections',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\WebhookUrls::class,
                    'label' => 'Webhook URLs',
                    'route' => '/admin/integrations/webhooks',
                    'required_methods' => ['mount'],
                    'ready_when' => 'Page displays webhook endpoints with copy buttons',
                ],
            ],
        ],
        'system' => [
            'label' => 'System Tools',
            'priority' => 1,
            'for_codecanyon_mvp' => true,
            'items' => [
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\System\SystemHealth::class,
                    'label' => 'System Health',
                    'route' => '/admin/system/health',
                    'required_methods' => ['mount'],
                    'ready_when' => 'Page shows system status, cache tools, logs viewer',
                ],
                [
                    'type' => 'page',
                    'class' => \App\Filament\Pages\System\CronSetup::class,
                    'label' => 'Cron Setup',
                    'route' => '/admin/system/cron',
                    'required_methods' => ['mount'],
                    'ready_when' => 'Page shows cron commands and heartbeat status',
                ],
            ],
        ],
    ],
];

